{% set name = "apache-airflow-providers-apache-druid" %}
{% set version = "4.3.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/apache_airflow_providers_apache_druid-{{ version }}.tar.gz
  sha256: 48205ed70d05886fc437c8fadd66d9a8f67900706bd5ad8c44abdd7f4778a235

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - flit-core ==3.12.0
    - pip
  run:
    - python >={{ python_min }}
    - apache-airflow >=2.10.0
    - apache-airflow-providers-common-sql >=1.26.0
    - pydruid >=0.6.6

test:
  imports:
    - airflow.providers.apache.druid
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/apache/airflow/
  summary: Provider package apache-airflow-providers-apache-druid for Apache Airflow
  license: Apache-2.0
  license_file: src/airflow/providers/apache/druid/LICENSE
  license_family: Apache
  doc_url: https://airflow.apache.org/docs/apache-airflow-providers-apache-druid/stable/index.html
  dev_url: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
