{% set name = "apache-airflow-providers-apache-druid" %}
{% set version = "3.12.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/apache_airflow_providers_apache_druid-{{ version }}.tar.gz
  sha256: 53d7ed3becd0d74eb5ee5372e1efcab0da96f2b94facb0d41e647e9bc5098e74

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9,<4.dev0
    - flit-core >=3.2,<4
    - pip
  run:
    - python >=3.9,<4.dev0
    - apache-airflow-providers-common-sql >=1.14.1
    - apache-airflow >=2.8.0
    - pydruid >=0.4.1

test:
  imports:
    - airflow.providers.apache.druid
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/apache/airflow/
  summary: Provider package apache-airflow-providers-apache-druid for Apache Airflow
  license: Apache-2.0
  license_file: airflow/providers/apache/druid/LICENSE
  license_family: Apache
  doc_url: https://airflow.apache.org/docs/apache-airflow-providers-apache-druid/stable/index.html
  dev_url: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
